eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

server:
  port: 9501

spring:
  application:
    name: user

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/product?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

  redis:
    database: 0
    host: localhost
    port: 6379